### ISSUE TITLE
named-units raison d'être?

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional-dk#46]
@dmcclean, I've reviewed your named-units-variants branch and lite this iteration better. However, as I asked in #7 regarding the named-units branch:

> Just to make sure we're on the same page: exactly what is the problem we are trying to solve (here)? To provide the UnitMap functionality? Any other goals of the named-units branch?

Can you provide a concrete use case (perhaps pseudo-code) of what named-units will enable that cannot be handled by other means (e.g. a specialised show function taking a map of desired units)? Thanks

**Comment by dmcclean** [comment]
OK, I think this is ready to be declared no longer a moving target.

If you have time, review the design that's in the named-units-2 branch in my fork.

It has everything we had mentioned wanting or is extensible without breaking changes to having everything.

The missing things being:

1. localization for unit names
2. a parser for unit names
3. fixed point types with statically tracked unit values

The first two are just about legwork, all the necessary machinery is in place.

The third one is held up by not having type rationals and by it creating a requirement to use the `PartialTypeSignatures` language extension for prettty much anyone who declares a `Unit`. However it is essentially compatible with this design, because it can be implemented by creating a third `Variant` for fixed point quantities. You need to add an extra type parameter to the `DUnit` variant though and to the `Unit` type synonym.

**Comment by dmcclean** [comment]
One drawback to this, which is in my opinion fairly minor, is that we don't have https://ghc.haskell.org/trac/ghc/ticket/8177 yet and may not ever.

The role signature of `Dimensional` should ideally be `nominal phantom representational` (and in master it is), but without 8177 it gets `nominal nominal nominal` in the named-units-2 branch.

**Comment by dmcclean** [comment]
Another note: I haven't merged the angles branch into the named-units-2 branch because its fate is also up in the air, but there isn't any problem in principle with doing so, AFAICS.

**Comment by dmcclean** [comment]
Made a change to remove existentials from the `UnitName` GADT. I think there was a discussion around here somewhere about whether tracking metric-ness of unit names was a step too far. I was leaning towards thinking it was, but actually most of the trickiness I was running into came from the existential types of the constructors and not from the phantom itself. Realized you don't need them because you can just use the `Weaken` constructor (through the `weaken` helper function) in a few more spots and voila they disappear.
