### ISSUE TITLE
Remove the Enum instance for Dimensional

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional-dk#47]
See #27.

**Comment by dmcclean** [comment]
Summarizing the previous thread, we are OK with getting rid of the (problematic) instance, but want some replacement for `enumFromThenTo`. Names were up in the air, as were treatment of endpoints, and whether to specify the size of the step or the number of steps.

There is some relevance to the kind of stuff that's in the `linear` and `vector-space` packages, but we probably want something here that doesn't take either of those dependencies.

Matlab has `linspace` where "`y = linspace(x1,x2,n)` generates `n` points. The spacing between the points is `(x2-x1)/(n-1)`." That seems like one possibility.

The previous thread also mentioned the possible desirability of a variant that generates an infinite list.

**Comment by dmcclean** [comment]
See also: http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html
http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

**Comment by bjornbm** [comment]
I'm leaning towards providing `nFromTo xi xf n` where n is the number of intermediate steps so that n == 0 gives `[xi, xf]`. I guess n < 0 would be an error, but unless we statically verify that n is a natural number  we could arguably just as well let n be the total number of steps and have n < 2 be an error??

It seems the latter would be consistent with Matlab's and Scipy's `linspace`, barring corner cases.

I don't feel strongly about the name, but don't necessarily understand the matlab/scipy names either.

We should probably provide a drop in replacement for `enumFromThenTo` as well, with the same possibly broken behavior as the underlying `a`, for those who want to define their own `Enum` instance.

**Comment by dmcclean** [comment]
Is there an advantage to just returning `[xi, xf]` if `n < 2`? Or `n == 1` -> `[xi]`, `n == 0` -> `[]`? Someone did put a type for term-level naturals in base, but for some reason it isn't the same type as the unlifted type of the type-level naturals. Also it's only in 4.8, and used by approximately nobody yet.

I also don't understand the matlab/scipy names. My guess is that the matlab people were smoking something when they made most of their names, this one is no exception, and the scipy people followed suit.

I have no problem with providing a drop in replacement for `enumFromThenTo`, but I'm not sure it helps too much in defining your own `Enum` instance, because the minimal implementation is `fromEnum, toEnum`. But (I think) `enumFromThenTo` is cool for fans of `RebindableSyntax`? So may be the others `enumFromThen`, and maybe `enumFromTo` (with some default number of steps) are OK as well? `enumFrom` seems like an inherently bad idea, because you need to pluck a step size out of thin air, and I doubt anyone is expecting `enumFrom (37 *~ second)` to be `[37, 37+5.4e-44, ...]`. :wink:

**Comment by bjornbm** [comment]
Ah, yes, you are right. It seems there is no way to win so perhaps we should put in as little as possible and just let people shoot themselves in the foot without our help?

A version of `nFromTo` seems pretty harmless and surprise-free though. I like the variant where `n` is the number of intermediate steps as it is total on the naturals and doesn't make an arbitrary choice about `n == 1` (`[xi]`, `[xf]`, or `[(xi + xf) / 2]`?). It also seems reasonable to treat `n < 0` as `n == 0` rather than throwing an error. This is my thinking right now, but I might end up swearing every time I use it and wishing `n` was the total number of elements …. Would `fromToByN` be a more descriptive name by the way?

**Comment by dmcclean** [comment]
I like that plan, and I think `nFromTo` is a good name.
