### ISSUE TITLE
Alternate approach for named-units

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional-dk#48]
Starting a new issue to not add another thread to #46.

@dmcclean wrote:

> I forgot to comment on internationalisation. I think that it might be best served by going from UnitName to UCUM and allowing people to internationalize by coming back out again? Direct structural recursion on UnitName is another possibility, but our name and abbreviation choices for non-SI units are arguably less standard.

I don't follow exactly what you envisioned in the first suggestion above. But yesterday evening I also had an idea about structural recursion and have drafted the https://github.com/bjornbm/dimensional-dk/tree/typenames branch.

The most interesting modules are [UnitNames](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/UnitNames.hs) and  [I18N](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/I18N.hs), but there are also some changes elsewhere including a change of the `Dimensional` type in [DK](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK.hs).

Type level "canonical" (our arbitrary choice) unit names are attached as ASTs to `Unit`s. When the unit is to be shown the type level AST is converted to a value level AST. The mechanics for this is in [UnitNames](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/UnitNames.hs).

The string representations for units and prefixes in the value level AST can then be translated to other language by use of a `Map`. See [I18N](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/I18N.hs), which also has the non-internationalised `showUnit` and `showIn`.

If you load [I18N](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/I18N.hs) you get the prelude too (right now) and can play around a little in ghci.

```
*Numeric.Units.Dimensional.DK.I18N> let x = 10 *~ (meter / second ^pos2)
*Numeric.Units.Dimensional.DK.I18N> x
10.0 m s^-2
*Numeric.Units.Dimensional.DK.I18N> showIn (kilo meter / second ^ pos2) x
"1.0e-2 km/s^2"
*Numeric.Units.Dimensional.DK.I18N> showIn (second ^ neg2 * kilo meter) x
"1.0e-2 s^-2 km"
*Numeric.Units.Dimensional.DK.I18N> long en_us (kilo meter / second ^ pos2)
"kilometer/second^2"
*Numeric.Units.Dimensional.DK.I18N> long en_gb (kilo meter / second ^ pos2)
"kilometre/second^2"
*Numeric.Units.Dimensional.DK.I18N> long sv_se (kilo meter / second ^ pos2)
"kilometer/sekund^2"
*Numeric.Units.Dimensional.DK.I18N> short sv_se (kilo meter / second ^ pos2)
"km/s^2"
*Numeric.Units.Dimensional.DK.I18N> showUnit (kilo meter / second * second)
"km/s*s"
*Numeric.Units.Dimensional.DK.I18N> showUnit (kilo meter / (second * second))
"km/(s s)"
*Numeric.Units.Dimensional.DK.I18N> showUnit (one * second)
"s"
*Numeric.Units.Dimensional.DK.I18N> showUnit (one / second)
"1/s"
```

I haven't thought through all corner cases there might be.

I haven't thought through naming very much, mostly just used what occurred to me first.

I've based the AST around your UnitName data type. The reason for `Atomic` and `PrefixableAtomic` eludes me but I kept them all the same as I'm sure you have thought things through. I didn't do any research either: perhaps someone (UCUM?) already has designed the perfect AST for describing unit presentation?

Most units and prefixes are missing from [SIUnits](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/SIUnit.hs), and even fewer (kilo, meter, second) are in [I18N](https://github.com/bjornbm/dimensional-dk/blob/typenames/Numeric/Units/Dimensional/DK/I18N.hs).

Does this approach have merit?

(The code could clearly use more documentation, and perhaps som restructuring in places. If it is too opaque for you to judge let me know and I'll try to document better.)

**Comment by dmcclean** [comment]
This I like very much.

Sticking points:

* Our needing to choose "canonical" unit names, and the lack of solid grounds upon which to make such a choice once you get outside of the SI. This also raises the issue of accidental collision between units defined in different packages. (It's possible to avoid that by pairing names with `Data.Unique`s, but there's no good story for creating them because of the `IO` requirement, and people will be confused when units with the same apparent name don't cancel with each other.) (There are other possible ways to avoid this, that are nice, but [they require TH at the location where new units are declared](https://hackage.haskell.org/package/template-haskell-2.10.0.0/docs/Language-Haskell-TH.html#v:thisModule).)
* A decision is needed on the prefixability question, and there are strong arguments on the merits on both sides, to the point where I don't know which way to turn.
* UCUM is an attractive source of (atomic, canonical, human-language-independent) names. And it would certainly make building a UCUM parser easy. But their name grammar did make some questionable decisions, some mentioned above, namely:
  1. allowing rational factors to appear in units
  2. allowing "annotations" with application defined semantics (although they are segregated somewhat, and the standard does say that it's fine for applications to interpret them as semantically void)
  3. They have "special units": "Those symbols that are used as units that imply a measurement on a scale other than a ratio scale (e.g., interval scale, logarithmic scale) are defined differently. These do not represent proper units as elements of the group (U,·). Therefore those special semantic entities are called special units, as opposed to proper units." (e.g. degC, dB). In our design these aren't units at all, because they don't measure quantities. (Of course, we have degC actually, but that's a different concept with the same name, it's the relative-only kind. UCUM models the non-zero-crossing and even non-linear "special units" in detail.)
  4. They have CGS electrostatic units defined with the dimensions they take in the SI basis.
  5. They have an ambiguous grammar caused by not having a delimiter between unit prefixes and the unit itself. Even with the canonical names they defined themselves, there [are a few such overlaps](http://unitsofmeasure.org/ucum.html#section-Summary-of-Conflicts), at least when people break the prefixability guidelines, but in the presence of user defined units obviously there could be more.

Addressing the simpler design decisions first:

5. Sigh. Return multiple results explicitly when parsing. In practice it doesn't come up, and it doesn't introduce much of an issue since you already need to deal with parse failures.

3 seems like an easy one. We don't do that. If we have a dimensional-dk-experimental module that is a UCUM parser, we have it return the UCUM AST. Our conversion function from UCUM AST to dynamic `Unit` returns `Left` something when passed such a beast.

4 I'm OK with. There's nothing saying we have to define these just because they did, but if we do we put them in a separate module.

2 is just a world of pain, because it's an even worse global namespace problem than the one with picking "canonical" names for user defined units. Having people pick different strings for "semantically" equivalent things is pretty much guaranteed (evidence: look at all the effort that's been spent on HL7 to try to tame it...). The names tend to name things that are logically dimensions but aren't statically available to the dimension checker. There are lots of other problems. Parse these, return them in the UCUM AST, and when converting to `Unit` just do what the standard condones and drop them on the floor.

Which brings us to 1, which might be the deal breaker.



(I will now advocate for a "learning to stop worrying and love the bomb" approach to number 1. I'm not as convinced of the correctness of what follows as I am of what has come so far.)

Arbitrary numbers in units aren't so bad. They still have names, so adopting a programmers hat you can still see how they are distinguished from quantities.

Moreover, and this is the key bit, they still have _static_ values. In fact, while I continue to believe as I did upthread that statically tracking unit _names_ isn't useful, statically tracking unit _values_ might be awesome. Indeed, statically tracking unit values is the essence of fixed point arithmetic as it's applied to dimensional values.

`Length Integer` isn't a very useful type, on one view, because it breaks the dimensional abstraction. "Everyone knows" it's in meters (or, for more complicated dimensions, at least it's in `siUnit`s...), but it's implied in a somewhat unhealthy way. On the other hand, with statically checked values using (the type-level version of...) the multiplication group from `exact-pi` package would be really nice. We would have machine-readable, statically checked, and dimensional types for things like "16 bit signed integer in milli-gee" and "32 bit unsigned integer in 2^-12 turns" and all the other stuff that comes up in contexts where dimensions and units are application critical but floating point isn't the right choice for the application, or wasn't the choice of legacy software.

**Comment by dmcclean** [comment]
Point 6: Their grammar doesn't exclude zero from the integer factors that are acceptable in units.

This is an intolerable atrocity, because it doesn't have a multiplicative inverse.

Filed http://unitsofmeasure.org/trac/ticket/172, since I couldn't find an existing one.

**Comment by bjornbm** [comment]
Thanks for the the in-depth analysis. I'm pretty much willing to trust your judgement on these questions, directed by your needs and keeping complexity a low as possible.

> 1. Sigh. Return multiple results explicitly when parsing. In practice it doesn't come up, and it doesn't introduce much of an issue since you already need to deal with parse failures.

I assume this comment was actually for 5?

> statically tracking unit _values_ might be awesome.

I can see how it could be. It is beyond my current needs but you are welcome to hash out what this could look like in code if you think it will pay off.

**Comment by dmcclean** [comment]
It was for 5, I messed up the markdown, which doesn't like starting ol's with numbers other than 1, apparently.

**Comment by dmcclean** [comment]
So using your type family concept above, I am making a named-units-2 branch (so I didn't have to delete my old one and can use it for comparison). It's working out pretty well, I think. Not quite ready for review but on the right track. It uses the UCUM-issued unit identifiers where they are available, our own where we have units they don't, and custom ones if end users need them. It has the ability to reduce it into units that exist in the UCUM before sending it over the wire, because it tracks who the issuing authority of the name was.

The exact values/fixed point thing is a whole other can of worms. Deserving of it's own thread if I take a pass at it. But right now I'm not going to, because type rationals are a prerequisite.
