### ISSUE TITLE
Updates to the NIST Guide

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#54]
The current version of the NIST guide at http://physics.nist.gov/Pubs/SP811/, where the documentation links point, appears to have been updated compared to when the documentation was written.

Several tables have changed names.

Also table 3 (the part at the end that was formerly in 3b) has added the katal (1 mole/second) as a unit of "catalytic activity". Do we have a specific objection to adding this, including the unit, dimension, and quantity aliases?

**Comment by dmcclean** [comment]
Also in limbo, the Dalton, which the guide says is an acceptable alias for the atomic mass unit.

**Comment by bjornbm** [comment]
Yes, I have noticed too that the guide has been updated since 2006, but
haven't taken the time to go through it in detail. Feel free to go ahead
and make changes like this. I have no objections at all to adding units in
general (barring possible ambiguities or very poorly defined ones) and
certainly not units in the NIST guide.

**Comment by dmcclean** [comment]
OK, will do. Didn't intend to imply that you should have taken the time to go through it, just happened to notice when I was cross-checking something while rearranging the documentation.
