### ISSUE TITLE
Are units ordered?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/dimensional-dk#74]
Right now we have `Eq` and `Ord` instances for `Dimensional`, so we have one for `Ord a => Unit d a`.

Is this desirable or objectionable? AFAICS, the NIST guide doesn't say anything about it one way or the other.

(Asking because it isn't automatic in the land of named units.)

**Comment by bjornbm** [comment]
I don't feel strongly about it and don't have a solid use case. Perhaps for building a UI where you want may want your units sorted by magnitude. Something along the lines of:

```haskell
units = [ (centi meter, "cm")
        , (meter, "m")
        , (kilo meter, "km")
        , (foot, "ft")
        ]

… populateMenu (sort units) …
```

(Which can surely be done much nicer with named units!)

But I'm not sure it is a realistic case and it could be worked around using something ugly like e.g.:

```haskell
sortUnits = map (\(_,u,s) -> (u,s)) . sort . map (\(u,s) -> (1*~ u, u, s))
```

If it is causing trouble for you I suggest you limit the `Ord` instance to quantities. We can always add it back later if we change our mind, and it seems like a preferable to have the option of adding functionality if a need is demonstrated, rather than being forced to remove it later because it was a bad idea in the first place.

**Comment by dmcclean** [comment]
It doesn't cause any trouble, but I'm tempted to leave it out anyway for the reason you mentioned.

It also strikes me as against the "spirit" of the NIST guide, but I admit that is just a vague impression.

**Comment by bjornbm** [comment]
Let’s leave it out then!
